name: Build and Test
on:
  push:
    branches:
      - master
      - gha
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls
      - name: Build
        run: python3 setup.py sdist
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/