name: Build and Test
on:
  push:
    branches:
      - master
      - gha
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build
        run: python3 setup.py sdist
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
  test:
    runs-on: ubuntu-latest
    name: Test
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox coveralls
      - name: Run Tox on All Supported Django and Python Versions
        run: tox
      - name: Generate Coverage Report
        run: |
          mkdir -p test-results/
          tox -e coverage
      - name: Send results to Coveralls
        run: COVERALLS_REPO_TOKEN=Q58WdUuZOi89XHyDeDsGE2lxUGQ2IfqP3 coveralls
      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/
